### ISSUE TITLE
Adding more crops and yield bonus

### ISSUE THREAD

**Issue by mattmcadoo** [Peppie84/FS25_BeesRevamp#4]
https://github.com/Peppie84/FS25_BeesRevamp/blob/c2f02e99277b36ca6e8645452468d1ff860ed2a7/FS25_BeesRevamp/src/main.lua#L47

Is that referenced line the single place to add more crops and their associated yield bonus with this mod?  Asking for verification and clarification of what I'm understanding in the code.

Thanks.

**Comment by Peppie84** [comment]
Hi @mattmcadoo , yes. This is the place where other crops can be added with there yield bonuses and needed hivesPerHectar. See the ls22 version: https://github.com/Peppie84/FS22_BeesRevamp/blob/4cb4deab7bf52ae3b6dc395e26742d7f5397963f/FS22_BeesRevamp/src/main.lua#L49

**Comment by Peppie84** [comment]
@mattmcadoo what crops should be added? Are there any new crops out there? Or should we close this ticket?

**Comment by mattmcadoo** [comment]
The base game crops of cotton, carrots, parsnips, red beets, grapes, olives, spinach, sorghum, and soybeans all seem to have real world yield bonus when bees are near them from the searching around that I've found.  Maybe sugar beets, but that's inconclusive from what I've seen.

For mod crops:

There's a modder by the name of Squigglzes (for example) that has made standalone cannabis mod for FS22, has a dedicated map in FS25 out now for it, and is still working on a standalone right now.

I'm not sure about a coffee bean mod yet for FS25.

I'm not counting anything in a greenhouse like strawberries, onions, lettuce, or garlic from the base game.

I would definitely suggest to include the Github URL in the info screen when the mod is released for letting others know about getting other crops added to the list.

**Comment by Peppie84** [comment]
You have to differentiate, for example the carrot. Yes there could be a yield bonus for them, ☝🏼  but only if you collect the seeds. In LS25 is no possibility to collect seeds out of the carrot. The carrot self will not be more or less with or without bees.

Also spinach, you harvest the spinach always without the flower. I found this : 
> At the very latest, when the spinach flowers, it should be harvested quickly. The flowers are not poisonous, they only reduce the quality of the leaves

Maybe sorghum and soybeans, i've to investigate some more for these.

For mod crops:
If there is a mod map whether in modhub or anywhere else, that has new crops that can be pollinated by bees with a yield bonus, i'll add them.


## Todo for me: Investigate for more crops
- [x] cotton ✔️ https://github.com/Peppie84/FS25_BeesRevamp/issues/4#issuecomment-2558407289 #8 
- [ ] carrots
- [ ] parsnips
- [ ] red beets
- [ ] grapes
- [ ] olives ✔️  https://github.com/Peppie84/FS25_BeesRevamp/issues/4#issuecomment-2558399965
- [ ] spinach
- [ ] sorghum
- [x] soybeans ✔️ https://github.com/Peppie84/FS25_BeesRevamp/issues/4#issuecomment-2564697157 #9 
- [ ] coffee bean
- [ ] cannabis

**Comment by mattmcadoo** [comment]
Here's the link to the map with add crop type of CANNABIS from what I can find in the XML files:  https://squigglze.itch.io/riverbend-springs-cannabis-edition

Found in tags like `<fruit type="CANNABIS" growthState="HARVESTREADY"/>`

Too bad all the other crop types (blueberries, raspberries, etc) I'm finding in mods are all in greenhouses...

**Comment by Peppie84** [comment]
## Olives (self-pollinating but bonus for cross-pollination)
organicfarming-italy ❌ 
> Olive trees are usually self-pollinating, meaning they do not require pollinating insects such as bees or wind for pollination. Most olive trees have both male and female flowers on the same plant, allowing for self-pollination.

https://www.organicfarming-italy.com/alles-ueber-olivenbaeume/#:~:text=Best%C3%A4ubung,Pflanze%2C%20was%20die%20Selbstbest%C3%A4ubung%20erm%C3%B6glicht.

GPT: ✔️ 
> Recommendation: 1 to 2 bee colonies per hectare.
Maximum efficiency: 2 bee colonies, especially for varieties with a high need for cross-pollination. This measure can increase olive tree yields by 10% to 20%.

M. Giovanetti: ✔️ 
> Olea europaea produces small, white flowers, and its pollination strategy is generally considered anemophilous. However, this assumption does not fit with frequent observations of bees, and other members of the Hymenoptera, visiting the flowers and actively collecting the pollen. Pollen is frequently recorded in honey and pollen samples of the honey bee, Apis mellifera, but is often omitted when lists of pollen/nectar sources are made. The honey bee has been already observed constantly visiting other anemophilous species to collect the abundant available pollen. Therefore, olive pollen could be a resource to be gathered. The present work examined bee frequency and behaviour on olive flowers in the north of Italy, in an area protected as a Regional Park, but where agriculture is also allowed. In the field, data on flower abundance and phenology (no. of flowers/inflorescence, no. of flowers in anthesis) were collected at the same time of data on bee behaviour (no. of flowers and inflorescences visited/time unit; resource collected; type of flower selected). The results indicate that the honey bee is actively using olive flowers as a source of pollen; moreover, bees pay constant visits and frequently change inflorescence, possibly increasing the pollination service paid to the plants.

https://www.ishs.org/ishs-article/1199_20

**Comment by Peppie84** [comment]
## Cotton (self-pollinating but bonus for cross-pollination)
GPT: ✔️ 
> To achieve a 5% to 35% increase in cotton yield, 1 to 3 bee colonies per hectare are typically required. The exact number depends on local conditions and the specific requirements of the cotton crop. Regular monitoring of bee activity and flower visits is important to ensure that pollination is taking place effectively.

2002 Beltwide Cotton conferences, Atlanta Jan 8-12: ✔️ 
> Upland cotton (Gossypium hirsutum L.) is self-fertile; the pollen needed to fertilize seeds and produce a mature boll can
come from the flower producing the boll. However, cotton breeders have long recognized that self-pollinated blossoms
usually donít produce quite as many seeds or as much lint as cross-pollinated flowers (Stephens1956). Several investigators
have demonstrated increased yields in cotton that was artificially cross-pollinated (e.g., Rose and Hughes 1955, Kohel 1968).
Cross-pollination of cotton is achieved almost exclusively by insects, cotton pollen being too heavy for effective wind
pollination. Several scientists have cited benefits derived by cotton from insect pollination. Shishikin (1946, 1952)
demonstrated that saturation pollination in areas at the rate of 1/2 colony of honey bees per acre increased cotton production
by 19.5% over areas depending only upon natural pollinators. Radoev and Bozhinov (1961) obtained an 11-24% greater
yield from cotton flowers freely visited by bees compared with flowers tied to exclude insects; there were more seeds per
boll, fewer motes and improved seed germination. Tanda (1984) found bee pollination to increase yield in two interplanted
varieties of Asian cotton (Gossypium arboreum L.).

https://www.cotton.org/beltwide/proceedings/getPDF.cfm?year=2002&paper=H160.pdf

**Comment by Peppie84** [comment]
## Soybean (self-pollinating but bonus for cross-pollination)

Sojafoerderring: ✔️ & ❌ 
> The small, inconspicuous soybean pods hardly open and produce little nectar and pollen, so the ecological value of the soybean for honeybees and other pollinating insects is correspondingly low. Soybean fields are only intensively pollinated when temperatures are high and nothing else is flowering. However, according to recent American studies, bee visits can then lead to a significant increase in yield due to improved pollination.
https://www.sojafoerderring.de/anbauratgeber/fruchtfolge/#:~:text=Die%20kleinen%2C%20unscheinbaren%20Sojab%C3%BCten%20%C3%B6ffnen,bl%C3%BCht%20werden%20Sojafelder%20intensiv%20beflogen.

GPT: ✔️
> Pollination by honey bees can increase soybean yields by 5% to 18%, depending on the variety and environmental conditions. The use of honey bee colonies in soybean fields is an effective method to improve both the quantity and quality of the crop.

Semanticscholar: ✔️
> In soybean fields with adjacent apiaries, yields were significantly higher at distances of up to 100 m from the apiaries than at greater distances, and in cage trials, 15% more beans were produced in cages with bees than in cages without bees.
https://www.semanticscholar.org/paper/Honey-Bee-Pollination-Increases-Soybean-Yields-in-Erickson-Berger/71a1c2db8b481a1decada82bf7aa198a968ac458

Springer.com: ✔️ 
> Soybean production in plots where flower-visiting insects were not excluded was higher than in plots where flower-visiting insects were excluded in year 1, when favorable environmental conditions occurred. The yield increase associated to honeybee visitation was positively related with seed number per unit area and negatively related with individual seed weight. Collectively, our results suggest an important role of honeybees in increasing the seed number per unit area of soybean under high yielding conditions.
https://link.springer.com/article/10.1007/s13592-017-0532-4#Sec13

**Comment by FirenzeIT** [comment]
Hi, i have found this important information about BeeHives and crops:

Bees are essential pollinators for many agricultural crops. Here are some of the main crops that benefit from pollination by bees:

Fruits: Apples, pears, peaches, apricots, cherries, strawberries, raspberries, blueberries, plums, pomegranates.

Vegetables: Zucchini, cucumbers, tomatoes, peppers, eggplant, artichokes, cauliflower, broccoli, Brussels sprouts.

Flowering plants: Sunflowers, girlande, daisies, marigolds, lavenders, hibiscus, roses, tulips.

Herbs: Basil, mint, rosemary, thyme, oregano, parsley, sage.

Oil crops: Almonds, walnuts, sesame, sunflowers (for oil).

Pollination by bees is essential for fruit and seed production, improving the quality and yield of crops.
